# Generated by Django 4.1 on 2023-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='types',
        ),
        migrations.AddField(
            model_name='question',
            name='yes_no',
            field=models.BooleanField(default=False, verbose_name="Yes or No question type. Please, don't write in the options below"),
        ),
    ]
