# Generated by Django 4.1 on 2023-12-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_question_types_question_yes_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'Identity tally'), ('PARIDAD', 'Parity tally'), ('BORDA', 'Borda count tally')], default='IDENTITY', max_length=10),
        ),
    ]
