name: Check Code Quality

on:
    pull_request: 
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                py-version: [3.9, 3.10]
                postgresql-version: [11.18-bullseye,14.9, 15]
        services:
            postgres:
                image: postgres:${{ matrix.postgresql-version }}
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.py-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.py-version }}
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            #FLAKE8
            - name: Run flake8 quality checks
              run: |
                pip install flake8
                flake 8 .
            #PYLINT, only in authentication folder for now
            - name: Run pylint quality checks
              run: |
                pip install pylint
                pylint authentication 
            #BANDIT
            - name: Run bandit quality checks
              run: |
                pip install bandit
                bandit -r .